---
- name: Playbook10
  hosts: all
  become: yes

  vars:
    mytext: "Privet"

  tasks:
    - name: Unregister Server from Load Balancer
      shell: echo This server {{inventory_hostname}} was deregistered from our Load Balancer, node name is {{ansible_nodename}} >> /home/log.txt
      # pre_tasks:
      #   - name: Instance De-register
      #     community.aws.ec2_elb:
      #       instance_id: "{{ ansible_ec2_instance_id }}"
      #       state: absent
      # post_tasks:
      # - name: Instance Register
      #   community.aws.ec2_elb:
      #     instance_id: "{{ ansible_ec2_instance_id }}"
      #     ec2_elbs: "{{ item }}"
      #     state: present
      #   loop: "{{ ec2_elbs }}"
      delegate_to: 127.0.0.1

    - name: Update my Database
      shell: echo UPDATING Database...
      run_once: true

    - name: Create file1
      copy:
        dest: /home/file1.txt
        content: |
          Text Line1, in file1
          Text Line2, in file1
          Text line3, {{ mytext }}
      delegate_to: linux3

    - name: Create file2
      copy:
        dest: /home/file2.txt
        content: |
          Text Line1, in file2
          Text Line2, in file2
          Text line3, {{ mytext }}

    - name: Reboot my Servers
      shell: sleep 3 && reboot now
      async: 1
      pool: 0

    - name: Wait till my server will come up online
      wait_for:
        host: "{{inventory_hostname}}"
        state: started
        delay: 5
        timeout: 40
      delegate_to: 127.0.0.1
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/reboot_module.html
