apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-claim
  labels:
    type: local
spec:
  resources:
    requests:
      storage: "100Mi" #{2:<Size>}
  #volumeMode: Filesystem 
  accessModes:
    - ReadWriteOnce
